# Copyright cocotb contributors
# Copyright (c) 2015 Potential Ventures Ltd
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# GPI_USERS no longer has any meaning: setting it to nonsense must
# neither break nor change the run (a warning is printed instead).
include ../../designs/sample_module/Makefile

COCOTB_TEST_MODULES = test_simple
export GPI_USERS = doesntexist
