# Copyright cocotb contributors
# Copyright (c) 2015 Potential Ventures Ltd
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# GPI_USERS is no longer supported: setting it to a bogus value must be
# ignored, so this simulation is expected to succeed.

include ../../designs/sample_module/Makefile

COCOTB_TEST_MODULES = test_simple
export GPI_USERS = doesntexist
